--Use CREDIT database to present a report in Excel with a chart to display Approval Rate and Total Credit Amount 
--by client's Age ranges (20 - 30, 31 - 40, 41 - 50, 51 - 60, 61 - 70, 70+). 

USE CREDIT 
GO
	
--OPTION 1: USING TEMPORARY TABLE & INNER JOIN
	--Making a temporary table 1 for calculating the approval rate
	SELECT ID_CLIENT, LS_APPLSTAT, AMT_CREDIT, 
			CASE WHEN LS_APPLSTAT IN ('ACT', 'APV') THEN 1
				 ELSE 0
			END APPROVAL_TEST
	INTO #TEMP1
	FROM APPLICATION2

	--Creating a temporary table 2 for clients over the age of 20 and using DATEDIFF function to calculate client's age by number of years.
	SELECT ID_CLIENT,    
			CASE WHEN DATEDIFF (YEAR, CAST (DATE_BIRTHDAY AS DATE), GETDATE()) <=30 THEN '20-30'
				 WHEN DATEDIFF (YEAR, CAST (DATE_BIRTHDAY AS DATE), GETDATE()) <=40 THEN '31-40'
				 WHEN DATEDIFF (YEAR, CAST (DATE_BIRTHDAY AS DATE), GETDATE()) <=50 THEN '41-50'
				 WHEN DATEDIFF (YEAR, CAST (DATE_BIRTHDAY AS DATE), GETDATE()) <=60 THEN '51-60'
				 WHEN DATEDIFF (YEAR, CAST (DATE_BIRTHDAY AS DATE), GETDATE()) <=70 THEN '61-70'
			     ELSE '70+'
			 END AGE_RANGE
	INTO #TEMP2
	FROM CLIENT2
	WHERE DATEDIFF (YEAR, CAST(DATE_BIRTHDAY AS DATE), GETDATE()) >= 20 ---> removing all of clients with Age < 20 or NULL.
		  AND DATE_BIRTHDAY IS NOT NULL

	--Joining 2 temporary tables 
	SELECT B.AGE_RANGE, 
		   1.0*SUM (A.APPROVAL_TEST)/COUNT(A.ID_CLIENT) APPOVAL_RATE,
		   SUM (CAST(AMT_CREDIT AS BIGINT)) TOTAL_AMOUNT
	FROM #TEMP1 A
	JOIN #TEMP2 B ON A.ID_CLIENT = B.ID_CLIENT
	GROUP BY B.AGE_RANGE
	ORDER BY B.AGE_RANGE
	
--OPTION 2: USING CTE TABLE & INNER JOIN
	WITH APPrate_Totalcredit AS (
	SELECT ar.AGE_RANGE,a.AMT_CREDIT,
			CASE WHEN a.LS_APPLSTAT IN ('ACT', 'APV') THEN 1
					 ELSE 0
				END APPSTAT
	FROM APPLICATION2 AS a
	
	INNER JOIN (
			SELECT *
			FROM CLIENT2
			WHERE DATEDIFF (YEAR, CAST (DATE_BIRTHDAY AS DATE), GETDATE()) >=20
				) AS b ON a.ID_CLIENT = b.ID_CLIENT --removing all of clients with Age < 20
	
	INNER JOIN (
				SELECT ID_CLIENT,
						CASE WHEN DATEDIFF (YEAR, CAST (DATE_BIRTHDAY AS DATE), GETDATE()) <=30 THEN '20-30'
							 WHEN DATEDIFF (YEAR, CAST (DATE_BIRTHDAY AS DATE), GETDATE()) <=40 THEN '31-40'
							 WHEN DATEDIFF (YEAR, CAST (DATE_BIRTHDAY AS DATE), GETDATE()) <=50 THEN '41-50'
							 WHEN DATEDIFF (YEAR, CAST (DATE_BIRTHDAY AS DATE), GETDATE()) <=60 THEN '51-60'
							 WHEN DATEDIFF (YEAR, CAST (DATE_BIRTHDAY AS DATE), GETDATE()) <=70 THEN '61-70'
							 ELSE '70+'
						END AGE_RANGE 
				FROM CLIENT2
				) AS ar ON ar.ID_CLIENT = a.ID_CLIENT)

		SELECT AGE_RANGE, 
			   COUNT (AGE_RANGE) NumAgeRange,
			   1.0*sum (APPSTAT) /count (AGE_RANGE) Approval_rate,
			   sum (CAST(AMT_CREDIT AS BIGINT)) Total_Credit_Amount
		FROM APPrate_Totalcredit
		GROUP BY AGE_RANGE
		ORDER BY AGE_RANGE 